site_name: ERNIE Docs
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/PaddlePaddle/ERNIE
repo_name: PaddlePaddle/ERNIE
edit_uri: edit/main/docs/source/
docs_dir: source
site_dir: site
strict: false

theme:
  name: material
  logo: assets/images/favicon.ico
  favicon: assets/images/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-2
        name: Switch to system preference
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow

plugins:
  - search
  - meta
  - awesome-nav
  - glightbox
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            Home: 首页

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Chinese
      link: /zh/
      lang: zh

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  # For content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  # For code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # For emoji and icons
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # For in page [TOC] (not sidebar)
  - toc:
      permalink: true
  # For math rendering
  - mdx_math:
      enable_dollar_delimiter: true

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML

use_directory_urls: false
