name: Container Check

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  work_dir: ${{ github.workspace }}

jobs:
  Lint:
    name: Lint
    runs-on: [self-hosted, 4gpu]
    permissions:
      pull-requests: write
      contents: read
      id-token: write
    steps:
      - name: Start Docker 
        run: |
          if [ ! "$(docker ps -q -f name=ERNIE_CI_Container)" ]; then
            echo "Starting container ERNIE_CI_Container"
            docker start ERNIE_CI_Container
          else
            echo "ERNIE_CI_Container already running"
          fi
      - name: Check Container
        run: 
          docker exec -t ERNIE_CI_Container /bin/bash -c '
          rm -rf tmp && mkdir tmp && cd tmp && \
          git clone https://github.com/PaddlePaddle/ERNIE.git  && \
          cd ERNIE  && \
          git fetch origin pull/${PR_ID}/head  && \
          git checkout -b PR_${PR_ID} FETCH_HEAD  && \
          git remote add upstream https://github.com/PaddlePaddle/ERNIE.git  && \
          git fetch upstream ${BRANCH}  && \
          git merge ${BRANCH}  && \
          make lint'
