name: Codestyle

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.pull_request.number }}
  BRANCH: ${{ github.event.pull_request.base.ref }}
  TASK: ERNIE-Codestyle-${{ github.event.pull_request.number }}
  container_name: ${TASK}-$(date +%Y%m%d-%H%M%S)
  docker_image: "iregistry.baidu-int.com/paddlecloud/base-images:paddlecloud-ubuntu20.04-gcc12.2-cuda12.3-cudnn9.0-nccl2.20.3.1-openmpi4.1.5"

jobs:
  codestyle:
    name: run-codestyle
    runs-on: [self-hosted, ernie-cpu]
    permissions:
      pull-requests: write
      contents: read
      id-token: write
    steps:
      - name: Run Container
        env:
          work_dir: ${{ github.workspace }}
          python_version: "3.10"
        run: |
          docker run -d -t --name ${container_name} \
            -v $work_dir:/workspace \
            -e BRANCH \
            -e PR_ID \
            -w /workspace ${docker_image}
      - name: Get Repo
        env:
          ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node16
          ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
          ACTIONS_ALLOW_UNSECURE_NODE_VERSION: true
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Repository
        env:
          work_dir: ${{ github.workspace }}
        run: |
          docker exec -t ${container_name} /bin/bash -c '
          cd ERNIE
          git config --global user.name "PaddleCI"
          git config --global user.email "paddle_ci@example.com"
          git pull
          git fetch origin pull/${PR_ID}/head  && \
          git checkout -b PR_${PR_ID} FETCH_HEAD  && \
          git remote add upstream https://github.com/PaddlePaddle/ERNIE.git  && \
          git fetch upstream ${BRANCH}  && \
          git merge ${BRANCH}  && \
          git diff --numstat ${BRANCH} -- | awk "{print \$NF}" && \
          '
        - name: Check Codestyle
        run: docker exec -t ERNIE_CI_Container /bin/bash -c '
          cd tmp/ERNIE 
          make lint'
