name: Codestyle Check

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  WorkPath: /home/paddle-1/actions-runner/_work/ERNIE/

jobs:
  Lint:
    name: Lint
    runs-on: [self-hosted, ernie-cpu]
    steps:
      - name: Cleanup Environment Cache
        run: 
          source ~/.bashrc
          rm -rf $WorkPath* $WorkPath.[!.]* $WorkPath..?*
      - name: Prepare Python Environment 
        run: 
          source ~/.bashrc
      - name: Check Codestyle
        run: 
          git config user.name "Paddle CI" && \
          git config user.email "paddle_ci@example.com" && \
          git clone --depth=1000 https://github.com/PaddlePaddle/ERNIE.git && \
          cd ERNIE/ && \
          git fetch origin pull/${PR_ID}/head && \
          git checkout -b PR_${PR_ID} FETCH_HEAD && \
          git remote add upstream https://github.com/PaddlePaddle/ERNIE.git && \
          git fetch upstream ${BRANCH} && \
          git merge ${BRANCH} && \
          make lint
