name: Test

on: [push, pull_request]

jobs:
  Test:
    name: Test
    runs-on: [self-hosted, 4gpu]
    steps:
      - name: Get Repo
        env:
          ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node16
          ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
          ACTIONS_ALLOW_UNSECURE_NODE_VERSION: true
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Start container
        run: |
          if [ ! "$(docker ps -q -f name=ERNIE_CI_Container)" ]; then
            echo "Starting container ERNIE_CI_Container"
            docker start ERNIE_CI_Container
          else
            echo "ERNIE_CI_Container already running"
          fi
      - name: Runing case
        run: docker exec -t ERNIE_CI_Container /bin/bash -c '
         make test'
