name: Test

on: [push, pull_request]

jobs:
  Test:
    name: Test
    runs-on: [self-hosted, 4gpu]
    steps:
      - name: Get Repo
        env:
          ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node16
          ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
          ACTIONS_ALLOW_UNSECURE_NODE_VERSION: true
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ${{ github.sha }}
      - name: Start container
        run: |
          if [ ! "$(docker ps -q -f name=ERNIE_CI_Container)" ]; then
            echo "Starting container ERNIE_CI_Container"
            docker start ERNIE_CI_Container
          else
            echo "ERNIE_CI_Container already running"
          fi
      - name: Prepare Model
        run: docker exec -t ERNIE_CI_Container /bin/bash -c '
          if [ ! -e "/workspace/eb45_random_model" ]; then
            echo "Copying ERNIE_Model to /workspace"
            cp -r /home/ERNIE_Model/* /workspace/
          fi'
      - name: Install erniekit
        run: docker exec -t ERNIE_CI_Container /bin/bash -c '
          pip install -e.'
      - name: Runing case
        run: docker exec -t ERNIE_CI_Container /bin/bash -c '
          make test'
      - name: Generate report
        run: docker exec -t ERNIE_CI_Container /bin/bash -c '
          if [ ! -e "/workspace/result" ]; then
            echo "Generating report"
            /workspace/allure-2.19.0/bin generate result -o report
          fi'
